<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$labelInfo = $this->setting('property_label_information');
?>
<dl>
<?php foreach ($values as $term => $propertyData): ?>
    <div class="property">
        <dt>
        <?php
            if ($propertyData['alternate_label']):
                echo $escape($propertyData['alternate_label']);
            else:
                echo $escape($translate($propertyData['property']->label())); 
            endif;?>
        <?php if ('term' === $labelInfo): ?>
        <span class="field-term">(<?php echo $escape($propertyData['property']->term()); ?>)</span>
        <?php elseif ('vocab' === $labelInfo): ?>
        <span class="field-term">(<?php echo $escape($propertyData['property']->vocabulary()->label()); ?>)</span>
        <?php endif; ?>
        </dt>
        <div class="values">
        <?php 
        foreach ($propertyData['values'] as $value): ?>
            <?php
            $valueType = $value->type();
            $class = ['value'];
            if ('resource' == $valueType || strpos($valueType, 'resource') !== false) {
                $class[] = 'resource';
                $class[] = $escape($value->valueResource()->resourceName());
            } elseif ('uri' == $valueType) {
                $class[] = 'uri';
            }
            if (!$value->isPublic()) {
                $class[] = 'private';
            }   
            ?>
            <dl class="<?
                echo implode(' ', $class); ?>" lang="<?php echo $escape($value->lang()); ?>">
                <?php
                // We want the transcription to be next to the image so build a table to display them adjacently
                if (1==1) {
                ?>
                <div>
                    <table id='transcription-table' class="transcription-table" style="border-collapse: unset;">
                        <tr>
                            <td class="transcription-img1" style="min-width: 500px;">
                                <?php echo $img;?> 
                            </td>
                            <td class="transcription-img2" style="min-width: 700px;">
                                <?php echo $img;?> 
                            </td>
                        </tr>
                    </table>
                </div>
                <style type="text/css">
                    /* Turning off the border and shadow at a higher level didn't work so a style tag was added */
                    .resource.show .media-render > a:only-child {
                        border: none;
                        -webkit-box-shadow: 0 0 0 0px rgb(255, 255, 255);
                        box-shadow: 0 0 0 0px rgb(255, 255, 255);}
                </style>
                <?php   
                } else {
                    if ($language = $value->lang()) { ?>
                        <span class="language">
                            <?php echo $language; ?>
                        </span>
                    <?php };?> <!--close inner if -->
                    <?php echo $value->asHtml();?>
                    <?php } ?> <!-- close else-->
                
            </dl>
        <?php endforeach; ?>
        </div>
    </div>
<?php endforeach; ?>
</dl>
<script type="text/javascript">
// find all properties on the page and move the transcript property to the top of the page.   
var elements = document.getElementsByClassName('property')

for(const item of elements){
  if (item.innerText.includes('transcript of')){
    elements[0].prepend(item)
  }
}
var media_renders = document.getElementsByClassName('media-render')
media_renders[1].hidden = true 
media_renders[2].hidden = true
var i_frames = document.getElementsByTagName('iframe')
i_frames[1].style.height = '700px'
</script>